<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="excel" nsURI="http://excel/1.0" nsPrefix="excel">
  <eClassifiers xsi:type="ecore:EClass" name="ExcelCell" eSuperTypes="#//ExcelStyleObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelRow" lowerBound="1"
        eType="#//ExcelRow" eOpposite="#//ExcelRow/excelCells"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelRow" eSuperTypes="#//ExcelStyleObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelSheet" lowerBound="1"
        eType="#//ExcelSheet" eOpposite="#//ExcelSheet/excelRows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelCells" upperBound="-1"
        eType="#//ExcelCell" containment="true" eOpposite="#//ExcelCell/excelRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelWorkbook">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelSheets" upperBound="-1"
        eType="#//ExcelSheet" containment="true" eOpposite="#//ExcelSheet/excelWorkbook"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelStyleObject" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelSheet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelWorkbook" lowerBound="1"
        eType="#//ExcelWorkbook" eOpposite="#//ExcelWorkbook/excelSheets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excelRows" upperBound="-1"
        eType="#//ExcelRow" containment="true" eOpposite="#//ExcelRow/excelSheet"/>
  </eClassifiers>
</ecore:EPackage>
